package com.skills.insuranceclaimsmanagementsystem.models;

public enum Authority {
    CAN_APPROVE_CLAIM, CAN_INVESTIGATE_REPORT,CAN_DISBURSE_PAYMENT,CAN_VIEW_CLAIMS,CAN_SUBMIT_CLAIM,CAN_UPDATE_CLAIM,CAN_VIEW_CLAIM
    ,CAN_VIEW_CLAIM_TYPES,CAN_VIEW_CLAIM_STATUS,
    CAN_VIEW_PAYMENT_STATUS,CAN_VIEW_PAYMENTS,CAN_VIEW_CLAIM_PAYMENTS,
    CAN_VIEW_CLAIM_REPORT,CAN_VIEW_CLAIM_TYPE_REPORT,
    CAN_VIEW_ROLES,CAN_VIEW_USERS,CAN_UPDATE_USERS,CAN_VIEW_USER,
    CAN_INITIATE_WORKFLOW,CAN_VIEW_WORKFLOW_STATUS,CAN_VIEW_WORKFLOW_STAGES,CAN_VIEW_WORKFLOW,
    CAN_VIEW_CLAIM_TYPE_BREAKDOWN,CAN_VIEW_CLAIM_STATUS_BREAKDOWN, CUSTOMER,INSURER
}
